FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
ARG CONTACT_TO_EMAIL
ARG CONTACT_FROM_EMAIL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_BOOKING_URL
ARG RESEND_API_KEY
ARG N8N_LEAD_WEBHOOK_URL
ARG EVOLUTION_API_BASE_URL
ARG EVOLUTION_API_INSTANCE_NAME
ARG EVOLUTION_API_KEY
ARG YCLOUD_API_KEY
ARG YCLOUD_WHATSAPP_FROM
ARG YCLOUD_WEBHOOK_SECRET
ARG CRM_AUTH_USER
ARG CRM_AUTH_PASSWORD
ARG CRM_AUTH_SECRET
ARG CRM_SELLER_USER
ARG CRM_SELLER_PASSWORD
ARG POSTGRES_URL
ARG DATABASE_URL
ARG POSTGRES_SSL
ARG GIT_SHA
ENV CONTACT_TO_EMAIL=$CONTACT_TO_EMAIL
ENV CONTACT_FROM_EMAIL=$CONTACT_FROM_EMAIL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_BOOKING_URL=$NEXT_PUBLIC_BOOKING_URL
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV N8N_LEAD_WEBHOOK_URL=$N8N_LEAD_WEBHOOK_URL
ENV EVOLUTION_API_BASE_URL=$EVOLUTION_API_BASE_URL
ENV EVOLUTION_API_INSTANCE_NAME=$EVOLUTION_API_INSTANCE_NAME
ENV EVOLUTION_API_KEY=$EVOLUTION_API_KEY
ENV YCLOUD_API_KEY=$YCLOUD_API_KEY
ENV YCLOUD_WHATSAPP_FROM=$YCLOUD_WHATSAPP_FROM
ENV YCLOUD_WEBHOOK_SECRET=$YCLOUD_WEBHOOK_SECRET
ENV CRM_AUTH_USER=$CRM_AUTH_USER
ENV CRM_AUTH_PASSWORD=$CRM_AUTH_PASSWORD
ENV CRM_AUTH_SECRET=$CRM_AUTH_SECRET
ENV CRM_SELLER_USER=$CRM_SELLER_USER
ENV CRM_SELLER_PASSWORD=$CRM_SELLER_PASSWORD
ENV POSTGRES_URL=$POSTGRES_URL
ENV DATABASE_URL=$DATABASE_URL
ENV POSTGRES_SSL=$POSTGRES_SSL
ENV GIT_SHA=$GIT_SHA
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ARG CONTACT_TO_EMAIL
ARG CONTACT_FROM_EMAIL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_BOOKING_URL
ARG RESEND_API_KEY
ARG N8N_LEAD_WEBHOOK_URL
ARG EVOLUTION_API_BASE_URL
ARG EVOLUTION_API_INSTANCE_NAME
ARG EVOLUTION_API_KEY
ARG YCLOUD_API_KEY
ARG YCLOUD_WHATSAPP_FROM
ARG YCLOUD_WEBHOOK_SECRET
ARG CRM_AUTH_USER
ARG CRM_AUTH_PASSWORD
ARG CRM_AUTH_SECRET
ARG CRM_SELLER_USER
ARG CRM_SELLER_PASSWORD
ARG POSTGRES_URL
ARG DATABASE_URL
ARG POSTGRES_SSL
ARG GIT_SHA
ENV NODE_ENV=production
ENV PORT=3000
ENV CONTACT_TO_EMAIL=$CONTACT_TO_EMAIL
ENV CONTACT_FROM_EMAIL=$CONTACT_FROM_EMAIL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_BOOKING_URL=$NEXT_PUBLIC_BOOKING_URL
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV N8N_LEAD_WEBHOOK_URL=$N8N_LEAD_WEBHOOK_URL
ENV EVOLUTION_API_BASE_URL=$EVOLUTION_API_BASE_URL
ENV EVOLUTION_API_INSTANCE_NAME=$EVOLUTION_API_INSTANCE_NAME
ENV EVOLUTION_API_KEY=$EVOLUTION_API_KEY
ENV YCLOUD_API_KEY=$YCLOUD_API_KEY
ENV YCLOUD_WHATSAPP_FROM=$YCLOUD_WHATSAPP_FROM
ENV YCLOUD_WEBHOOK_SECRET=$YCLOUD_WEBHOOK_SECRET
ENV CRM_AUTH_USER=$CRM_AUTH_USER
ENV CRM_AUTH_PASSWORD=$CRM_AUTH_PASSWORD
ENV CRM_AUTH_SECRET=$CRM_AUTH_SECRET
ENV CRM_SELLER_USER=$CRM_SELLER_USER
ENV CRM_SELLER_PASSWORD=$CRM_SELLER_PASSWORD
ENV POSTGRES_URL=$POSTGRES_URL
ENV DATABASE_URL=$DATABASE_URL
ENV POSTGRES_SSL=$POSTGRES_SSL
ENV GIT_SHA=$GIT_SHA

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
